# Generated by Django 4.2.4 on 2023-09-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date_difference_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateDifference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.CharField(max_length=70)),
                ('to_date', models.CharField(max_length=70)),
            ],
        ),
        migrations.DeleteModel(
            name='Date1',
        ),
        migrations.DeleteModel(
            name='Date2',
        ),
    ]
