# Generated by Django 4.2.4 on 2023-09-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date_difference_app', '0002_datedifference_delete_date1_delete_date2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datedifference',
            name='from_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='datedifference',
            name='to_date',
            field=models.DateField(null=True),
        ),
    ]
