# Generated by Django 4.2.4 on 2023-09-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('age_calculator_app', '0004_remove_agecalculator_birthday_date_agecalculator_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agecalculator',
            name='day',
        ),
        migrations.RemoveField(
            model_name='agecalculator',
            name='month',
        ),
        migrations.RemoveField(
            model_name='agecalculator',
            name='year',
        ),
        migrations.AddField(
            model_name='agecalculator',
            name='birthday_date',
            field=models.DateField(null=True),
        ),
    ]
