# Generated by Django 4.2.4 on 2023-09-19 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('date_conversion_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dateconversion',
            old_name='day',
            new_name='date_conversion',
        ),
        migrations.RemoveField(
            model_name='dateconversion',
            name='month_miladi',
        ),
        migrations.RemoveField(
            model_name='dateconversion',
            name='month_shamsy',
        ),
        migrations.RemoveField(
            model_name='dateconversion',
            name='year',
        ),
    ]
