# Generated by Django 4.2.4 on 2023-10-05 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date_conversion_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateconversion',
            name='conversion_type',
            field=models.CharField(choices=[('persian to international', 'persian to international'), ('international to persian', 'international to persian')], default='international_to_persian', max_length=200, null=True),
        ),
    ]
