# Generated by Django 4.2.4 on 2023-09-19 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date_conversion_app', '0002_rename_day_dateconversion_date_conversion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dateconversion',
            old_name='date_conversion',
            new_name='international_date',
        ),
        migrations.AddField(
            model_name='dateconversion',
            name='persian_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='dateconversion',
            name='conversion_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'persian to international'), (2, 'international to persian')], default=1, null=True),
        ),
    ]
