# Generated by Django 4.2.4 on 2023-09-23 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date_conversion_app', '0003_rename_date_conversion_dateconversion_international_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateconversion',
            name='persian_date',
            field=models.DateTimeField(null=True),
        ),
    ]
