# Generated by Django 4.2.4 on 2023-09-24 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date_conversion_app', '0004_alter_dateconversion_persian_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateconversion',
            name='international_date',
            field=models.PositiveSmallIntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='dateconversion',
            name='persian_date',
            field=models.PositiveSmallIntegerField(choices=[(1, 'فروردین'), (2, 'اردیبهشت'), (3, 'خرداد'), (4, 'تیر'), (5, 'مرداد'), (6, 'شهریور'), (7, 'مهر'), (8, 'آبان'), (9, 'آذر'), (10, 'دی'), (11, 'بهمن'), (12, 'اسفند')], default=1, null=True),
        ),
    ]
