# Generated by Django 4.2.4 on 2023-09-24 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date_conversion_app', '0005_alter_dateconversion_international_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dateconversion',
            old_name='international_date',
            new_name='international_month',
        ),
        migrations.RenameField(
            model_name='dateconversion',
            old_name='persian_date',
            new_name='persian_month',
        ),
        migrations.AddField(
            model_name='dateconversion',
            name='day',
            field=models.IntegerField(max_length=31, null=True),
        ),
        migrations.AddField(
            model_name='dateconversion',
            name='year',
            field=models.IntegerField(max_length=4, null=True),
        ),
    ]
