# Generated by Django 4.2.4 on 2023-09-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date_conversion_app', '0006_rename_international_date_dateconversion_international_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateconversion',
            name='conversion_type',
            field=models.CharField(choices=[('persian to international', 'persian to international'), ('international to persian', 'international to persian')], default='persian to international', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dateconversion',
            name='day',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='dateconversion',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
