# Generated by Django 4.2.4 on 2023-09-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date_conversion_app', '0007_alter_dateconversion_conversion_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dateconversion',
            name='conversion_type',
            field=models.CharField(choices=[('persian to international', 'persian to international'), ('international to persian', 'international to persian')], max_length=200, null=True),
        ),
    ]
